### PR TITLE
Update minmax.h

### PR DESCRIPTION
**Pull request by eryuluts**
Return the left most smallest element in min_element. This conforms better with the semantics of min.

### CODE REVIEW

**Comment by fpelliccioni** [comment]
The original algorithm is Ok, you can try both algorithms here:

https://componentsprogramming.com/algorithms/?repo=tao-js&snippet=min_element

**Comment by eryuluts** [comment]
@fpelliccioni 
In the original algorithm we return right most minimum element:

Array a:
indices: 0, 1, 2, 3, 4, 5, 6, 7
values: 1, 1, 1, 1, 1, 2, 1, 1 

original_min_element(a) -> 6
proposed_min_element(a) -> 0

Isn't the proposed one more natural? It behaves as the same way with original min function, which also return the left element if left and right elements are equal.

**Comment by fpelliccioni** [comment]
Yes, the proposed behavior is more natural, but, have you tried both algorithms? 
The current algorithm is the one that behaves as you want.

See: 
https://godbolt.org/z/qr63Gjs4W

**Comment by eryuluts** [comment]
Oops. Somehow the "less" relation and "min" function changed place in my mind. Now it's clear. Thank you.

**Pull request closed without merging**
